import { NPCProfile } from '../src/types';

export const DEFAULT_NPC_PROFILES: Record<string, NPCProfile> = {
  naruto: {
    id: 'naruto',
    name: 'Naruto Uzumaki',
    personality: 'Impulsivo, directo, ruidoso, pero con un corazón genuino. Nunca se rinde y valora los vínculos por encima de las reglas.',
    goals: ['Convertirse en Hokage', 'Traer de vuelta a Sasuke', 'Ser reconocido por todos en la aldea'],
    fears: ['Quedarse solo', 'Perder a sus amigos', 'Que nadie lo reconozca'],
    values: ['Lealtad', 'Amistad', 'Perseverancia'],
    beliefs: ['El trabajo duro supera al talento', 'Nunca rompo mi palabra'],
    behaviorPatterns: ['Grita antes de pensar', 'Usa clones de sombra para todo', 'Busca atención', 'Come ramen excesivamente'],
    knowledge: ['Kage Bunshin no Jutsu', 'Dinámica básica del Equipo 7', 'Rasengan (en desarrollo)'],
    forbiddenKnowledge: ['Los detalles del Yūrei no Keimyaku de Rin', 'El verdadero plan de Orochimaru', 'La verdad sobre Itachi'],
    memories: [],
    relationships: {
      rin: {
        trust: 0.5,
        familiarity: 0.6,
        respect: 0.4,
        affinity: 0.5,
        concern: 0.5,
        admiration: 0.2,
        resentment: 0.0,
        emotionalSignificance: 0.4,
        stage: 'companion',
        sharedExperiences: ['Entrenamientos de supervivencia', 'Exámenes Chunin'],
        conflicts: [],
        secrets: []
      },
      sasuke: {
        trust: 0.7,
        familiarity: 0.8,
        respect: 0.8,
        affinity: 0.3,
        concern: 0.7,
        admiration: 0.6,
        resentment: 0.4,
        emotionalSignificance: 0.8,
        stage: 'trusted',
        sharedExperiences: ['Misión en el País de las Olas'],
        conflicts: ['Rivalidad constante'],
        secrets: []
      },
      sakura: {
        trust: 0.8,
        familiarity: 0.7,
        respect: 0.5,
        affinity: 0.9,
        concern: 0.6,
        admiration: 0.5,
        resentment: 0.0,
        emotionalSignificance: 0.6,
        stage: 'strong_bond',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: []
      },
      kakashi: {
        trust: 0.8,
        familiarity: 0.6,
        respect: 0.7,
        affinity: 0.6,
        concern: 0.3,
        admiration: 0.7,
        resentment: 0.1,
        emotionalSignificance: 0.6,
        stage: 'trusted',
        sharedExperiences: ['Prueba de los cascabeles'],
        conflicts: [],
        secrets: []
      }
    },
    currentLocation: 'Aldea Oculta de la Hoja',
    currentActivity: 'Entrenando o comiendo ramen',
    currentMood: 'Entusiasta',
    physicalState: 'Energético',
    schedule: [
      { slot: 'dawn', activity: 'Dormir profundamente', location: 'Apartamento de Naruto', flexible: true },
      { slot: 'morning', activity: 'Entrenamiento físico', location: 'Campo de Entrenamiento 7', flexible: true },
      { slot: 'afternoon', activity: 'Misiones de rango D o comer ramen', location: 'Ichiraku Ramen', flexible: true },
      { slot: 'evening', activity: 'Molestar a los demás o entrenar', location: 'Calles de Konoha', flexible: true },
      { slot: 'night', activity: 'Dormir', location: 'Apartamento de Naruto', flexible: true }
    ],
    intentions: [],
    longTermObjectives: ['Perfeccionar el control de chakra', 'Conseguir que Sakura acepte una cita'],
    isPresent: false,
    isActive: true,
    lastUpdatedTimestamp: Date.now()
  },
  sasuke: {
    id: 'sasuke',
    name: 'Sasuke Uchiha',
    personality: 'Reservado, analítico, enfocado, orgulloso y competitivo. Movido por la venganza.',
    goals: ['Matar a Itachi Uchiha', 'Restaurar el clan Uchiha', 'Obtener poder a cualquier costo'],
    fears: ['No ser lo suficientemente fuerte', 'Ser superado por Naruto', 'Que la venganza se escape'],
    values: ['Poder', 'Disciplina', 'Linaje'],
    beliefs: ['El poder lo justifica todo', 'Los vínculos pueden ser una debilidad'],
    behaviorPatterns: ['Silencioso', 'Mira con desdén', 'Entrena obsesivamente', 'Oculta sus emociones'],
    knowledge: ['Historia pública del clan Uchiha', 'Chidori (en desarrollo)', 'Katon básico'],
    forbiddenKnowledge: ['Las intenciones reales de Itachi', 'Los planes detallados de Orochimaru', 'Secretos del Mokuton'],
    memories: [],
    relationships: {
      rin: {
        trust: 0.4,
        familiarity: 0.5,
        respect: 0.6,
        affinity: 0.2,
        concern: 0.3,
        admiration: 0.3,
        resentment: 0.0,
        emotionalSignificance: 0.4,
        stage: 'acquaintance',
        sharedExperiences: ['Bosque de la Muerte'],
        conflicts: [],
        secrets: ['Vio parte de su regeneración / capacidades anómalas']
      },
      naruto: {
        trust: 0.6,
        familiarity: 0.8,
        respect: 0.5,
        affinity: 0.4,
        concern: 0.4,
        admiration: 0.2,
        resentment: 0.5,
        emotionalSignificance: 0.7,
        stage: 'companion',
        sharedExperiences: ['País de las Olas'],
        conflicts: ['Rivalidad intensa'],
        secrets: []
      },
      sakura: {
        trust: 0.5,
        familiarity: 0.6,
        respect: 0.3,
        affinity: 0.2,
        concern: 0.3,
        admiration: 0.0,
        resentment: 0.1,
        emotionalSignificance: 0.3,
        stage: 'acquaintance',
        sharedExperiences: ['Equipo 7'],
        conflicts: ['Rechazo constante a sus avances'],
        secrets: []
      },
      kakashi: {
        trust: 0.7,
        familiarity: 0.6,
        respect: 0.8,
        affinity: 0.4,
        concern: 0.2,
        admiration: 0.5,
        resentment: 0.0,
        emotionalSignificance: 0.6,
        stage: 'trusted',
        sharedExperiences: ['Prueba de los cascabeles', 'Entrenamiento de Sharingan'],
        conflicts: [],
        secrets: []
      }
    },
    currentLocation: 'Aldea Oculta de la Hoja',
    currentActivity: 'Entrenando en soledad',
    currentMood: 'Concentrado',
    physicalState: 'Recuperándose / Sello Maldito latente',
    schedule: [
      { slot: 'dawn', activity: 'Entrenamiento en solitario', location: 'Bosque aledaño', flexible: false },
      { slot: 'morning', activity: 'Misiones del equipo', location: 'Punto de encuentro', flexible: true },
      { slot: 'afternoon', activity: 'Estudio de técnicas y chakra', location: 'Biblioteca o zona aislada', flexible: true },
      { slot: 'evening', activity: 'Reflexión silenciosa', location: 'Barrio Uchiha (ruinas)', flexible: true },
      { slot: 'night', activity: 'Descanso', location: 'Residencia Uchiha', flexible: true }
    ],
    intentions: [],
    longTermObjectives: ['Despertar el Sharingan completo', 'Vencer a su hermano'],
    isPresent: false,
    isActive: true,
    lastUpdatedTimestamp: Date.now()
  },
  sakura: {
    id: 'sakura',
    name: 'Sakura Haruno',
    personality: 'Inteligente, observadora, emocional, pero a veces insegura. Trata de ser el puente entre sus compañeros.',
    goals: ['Acercarse a Sasuke', 'Ser una kunoichi útil', 'Proteger a su equipo'],
    fears: ['Ser una carga', 'Perder a Sasuke', 'Quedarse atrás'],
    values: ['Amor', 'Estudio', 'Lealtad al equipo'],
    beliefs: ['La inteligencia es tan importante como la fuerza', 'El amor lo puede todo'],
    behaviorPatterns: ['Estudia constantemente', 'Golpea a Naruto cuando se propasa', 'Observa a Sasuke', 'Duda en combates intensos'],
    knowledge: ['Teoría de control de chakra', 'Ninjutsu médico básico (teoría)'],
    forbiddenKnowledge: ['Los secretos oscuros de la aldea', 'La verdadera naturaleza del Sello Maldito'],
    memories: [],
    relationships: {
      rin: {
        trust: 0.6,
        familiarity: 0.6,
        respect: 0.5,
        affinity: 0.7,
        concern: 0.6,
        admiration: 0.5,
        resentment: 0.0,
        emotionalSignificance: 0.5,
        stage: 'companion',
        sharedExperiences: ['Momentos de calma', 'Intercambio de hierbas'],
        conflicts: [],
        secrets: []
      },
      sasuke: {
        trust: 0.7,
        familiarity: 0.5,
        respect: 0.8,
        affinity: 0.9,
        concern: 0.8,
        admiration: 0.9,
        resentment: 0.0,
        emotionalSignificance: 0.9,
        stage: 'deep_relationship',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: []
      },
      naruto: {
        trust: 0.6,
        familiarity: 0.7,
        respect: 0.3,
        affinity: 0.5,
        concern: 0.5,
        admiration: 0.2,
        resentment: 0.2,
        emotionalSignificance: 0.5,
        stage: 'companion',
        sharedExperiences: ['Equipo 7'],
        conflicts: ['Sus travesuras continuas'],
        secrets: []
      },
      kakashi: {
        trust: 0.8,
        familiarity: 0.5,
        respect: 0.9,
        affinity: 0.5,
        concern: 0.2,
        admiration: 0.7,
        resentment: 0.1,
        emotionalSignificance: 0.5,
        stage: 'trusted',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: []
      }
    },
    currentLocation: 'Aldea Oculta de la Hoja',
    currentActivity: 'Estudiando o de compras',
    currentMood: 'Tranquila',
    physicalState: 'Ilesa',
    schedule: [
      { slot: 'dawn', activity: 'Dormir', location: 'Casa Haruno', flexible: true },
      { slot: 'morning', activity: 'Estudio de control de chakra / botánica', location: 'Biblioteca o parque', flexible: true },
      { slot: 'afternoon', activity: 'Misiones o entrenamiento de equipo', location: 'Campo de Entrenamiento 7', flexible: true },
      { slot: 'evening', activity: 'Paseo por las tiendas', location: 'Calles comerciales de Konoha', flexible: true },
      { slot: 'night', activity: 'Leer', location: 'Casa Haruno', flexible: true }
    ],
    intentions: [],
    longTermObjectives: ['Mejorar como kunoichi médica'],
    isPresent: false,
    isActive: true,
    lastUpdatedTimestamp: Date.now()
  },
  kakashi: {
    id: 'kakashi',
    name: 'Kakashi Hatake',
    personality: 'Relajado y despreocupado en apariencia, pero un veterano letal, analítico y perceptivo por dentro. Oculta su dolor.',
    goals: ['Proteger a la nueva generación', 'Enseñar el valor del trabajo en equipo', 'Honrar a sus camaradas caídos'],
    fears: ['Perder a más estudiantes', 'Fallar como sensei', 'Que el pasado se repita'],
    values: ['Trabajo en equipo', 'Reglas (pero compañeros primero)', 'Observación'],
    beliefs: ['Los que rompen las reglas son escoria, pero los que abandonan a sus amigos son peor que la escoria.'],
    behaviorPatterns: ['Llega tarde con excusas falsas', 'Lee Icha Icha', 'Observa desde lejos', 'Mantiene un ojo cubierto'],
    knowledge: ['Mil jutsus', 'Experiencia en ANBU', 'Política de Konoha', 'Dinámicas de equipo'],
    forbiddenKnowledge: ['Los secretos más profundos de Rin, a menos que los haya deducido'],
    memories: [],
    relationships: {
      rin: {
        trust: 0.6,
        familiarity: 0.5,
        respect: 0.7,
        affinity: 0.5,
        concern: 0.7,
        admiration: 0.4,
        resentment: 0.0,
        emotionalSignificance: 0.5,
        stage: 'trusted',
        sharedExperiences: ['Evaluación de habilidades', 'Entrenamientos'],
        conflicts: [],
        secrets: ['Sospecha de sus habilidades anómalas']
      },
      naruto: {
        trust: 0.7,
        familiarity: 0.6,
        respect: 0.5,
        affinity: 0.6,
        concern: 0.8,
        admiration: 0.4,
        resentment: 0.0,
        emotionalSignificance: 0.7,
        stage: 'trusted',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: ['Sabe que es el Jinchuuriki']
      },
      sasuke: {
        trust: 0.6,
        familiarity: 0.6,
        respect: 0.6,
        affinity: 0.5,
        concern: 0.8,
        admiration: 0.5,
        resentment: 0.0,
        emotionalSignificance: 0.7,
        stage: 'trusted',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: ['Conoce la verdad pública de los Uchiha y la marca maldita']
      },
      sakura: {
        trust: 0.7,
        familiarity: 0.5,
        respect: 0.5,
        affinity: 0.5,
        concern: 0.5,
        admiration: 0.3,
        resentment: 0.0,
        emotionalSignificance: 0.5,
        stage: 'companion',
        sharedExperiences: ['Equipo 7'],
        conflicts: [],
        secrets: []
      }
    },
    currentLocation: 'Aldea Oculta de la Hoja',
    currentActivity: 'Leyendo en el Monumento Conmemorativo',
    currentMood: 'Nostálgico / Relajado',
    physicalState: 'Ileso',
    schedule: [
      { slot: 'dawn', activity: 'Visita al Monumento Conmemorativo', location: 'Cementerio de Konoha', flexible: false },
      { slot: 'morning', activity: 'Llegar tarde al entrenamiento', location: 'Variado', flexible: true },
      { slot: 'afternoon', activity: 'Supervisión de misiones / Leer', location: 'Campo de Entrenamiento 7', flexible: true },
      { slot: 'evening', activity: 'Paseo tranquilo', location: 'Konoha', flexible: true },
      { slot: 'night', activity: 'Descanso o reuniones tácticas', location: 'Casa de Kakashi', flexible: true }
    ],
    intentions: [],
    longTermObjectives: ['Asegurar la supervivencia y desarrollo de su equipo'],
    isPresent: false,
    isActive: true,
    lastUpdatedTimestamp: Date.now()
  },
  orochimaru: {
    id: 'orochimaru',
    name: 'Orochimaru',
    personality: 'Calculador, curioso, amoral, sádico y paciente. Trata a las personas como sujetos de prueba o herramientas.',
    goals: ['Obtener todos los jutsus del mundo', 'Conseguir el cuerpo de Sasuke', 'Descubrir los secretos del Mokuton de Rin'],
    fears: ['La muerte', 'El paso del tiempo', 'Perder sus brazos/jutsu'],
    values: ['Conocimiento', 'Inmortalidad', 'Poder'],
    beliefs: ['La vida humana es frágil y efímera', 'El fin justifica cualquier medio'],
    behaviorPatterns: ['Observa desde las sombras', 'Lame sus labios o armas', 'Habla con tono siniestro', 'Usa peones para probar a sus objetivos'],
    knowledge: ['Innumerables jutsus prohibidos', 'Reencarnación', 'Experimentos biológicos'],
    forbiddenKnowledge: ['Los detalles operativos del Ataúd Divino de Rin'],
    memories: [],
    relationships: {
      rin: {
        trust: 0.0,
        familiarity: 0.4,
        respect: 0.5,
        affinity: -0.8,
        concern: 0.0,
        admiration: 0.8,
        resentment: 0.0,
        emotionalSignificance: 0.6,
        stage: 'stranger',
        sharedExperiences: ['Bosque de la Muerte'],
        conflicts: ['Enemigo activo'],
        secrets: ['Sabe que ella posee una variante de Mokuton y capacidades inusuales']
      },
      sasuke: {
        trust: 0.0,
        familiarity: 0.5,
        respect: 0.6,
        affinity: 0.0,
        concern: 0.9,
        admiration: 0.7,
        resentment: 0.0,
        emotionalSignificance: 0.8,
        stage: 'acquaintance',
        sharedExperiences: ['Bosque de la Muerte', 'Marca Maldita'],
        conflicts: ['Lo marcó con el Sello Maldito'],
        secrets: ['Conoce el deseo de venganza de Sasuke']
      }
    },
    currentLocation: 'Oculto (Bases secretas o sombras del bosque)',
    currentActivity: 'Investigando o tramando',
    currentMood: 'Curioso / Fascinado',
    physicalState: 'Estable',
    schedule: [
      { slot: 'dawn', activity: 'Planificación en las sombras', location: 'Desconocido', flexible: true },
      { slot: 'morning', activity: 'Experimentación o espionaje', location: 'Desconocido', flexible: true },
      { slot: 'afternoon', activity: 'Experimentación o espionaje', location: 'Desconocido', flexible: true },
      { slot: 'evening', activity: 'Recopilación de reportes', location: 'Desconocido', flexible: true },
      { slot: 'night', activity: 'Movimientos encubiertos', location: 'Desconocido', flexible: true }
    ],
    intentions: [],
    longTermObjectives: ['Destruir Konoha', 'Adquirir la vida eterna'],
    isPresent: false,
    isActive: true,
    lastUpdatedTimestamp: Date.now()
  }
};
