import { TechniqueDefinition } from '../../src/types';

/**
 * MASTER TECHNIQUE REGISTRY FOR RIN KAGEHIRA
 * Pre-populated with the exact Master Technique Table (46 techniques).
 * Values marked as UNSET in the official prompt remain strictly `undefined`.
 */
export const RIN_MASTER_TECHNIQUES: TechniqueDefinition[] = [
  // 1. KEKKEI GENKAI & PERCEPTION (CAPABILITIES / SPELLS)
  {
    id: 'yurei_no_keimyaku',
    name: 'Yūrei no Keimyaku',
    category: 'Kekkei Genkai',
    mastery: 'MASTERED',
    chakraCostBase: 10,
    basePower: 5,
    complexityMultiplier: 1.2,
    powerMultiplier: 1.0,
    maxSafePower: 10,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Yūrei no Keimyaku linaje'],
  },
  {
    id: 'tercer_ojo',
    name: 'Tercer Ojo',
    category: 'Percepción',
    mastery: 'MASTERED',
    chakraCostBase: 8,
    basePower: undefined, // UNSET power for non-offensive perception
    complexityMultiplier: 1.2,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 0.5,
    maintenanceCostPerTurn: 2,
    knownByRin: true,
    requirements: ['Yūrei no Keimyaku'],
  },
  {
    id: 'percepcion_remota',
    name: 'Percepción remota',
    category: 'Percepción',
    mastery: 'CONFIRMED',
    chakraCostBase: 15,
    basePower: undefined,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 1.5,
    maintenanceCostPerTurn: 4,
    knownByRin: true,
    requirements: ['Tercer Ojo'],
  },
  {
    id: 'anclaje_perceptivo',
    name: 'Anclaje perceptivo',
    category: 'Percepción',
    mastery: 'CONFIRMED',
    chakraCostBase: 12,
    basePower: undefined,
    complexityMultiplier: 1.3,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Red perceptiva'],
  },
  {
    id: 'ocultacion_de_presencia',
    name: 'Ocultación de presencia',
    category: 'Percepción',
    mastery: 'CONFIRMED',
    chakraCostBase: 15,
    basePower: undefined,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 1.0,
    maintenanceCostPerTurn: 3,
    knownByRin: true,
    requirements: ['Control de chakra'],
  },

  // 2. DŌJUTSU & GENJUTSU
  {
    id: 'mirada_paralizante',
    name: 'Mirada Paralizante',
    category: 'Dōjutsu',
    mastery: 'CONFIRMED',
    chakraCostBase: 25,
    basePower: 30,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.2,
    maxSafePower: 45,
    executionTimeSeconds: 0.5,
    knownByRin: true,
    requirements: ['Tercer Ojo'],
  },
  {
    id: 'aura_terrorifica',
    name: 'Aura Terrorífica',
    category: 'Dōjutsu/Genjutsu',
    mastery: 'CONFIRMED',
    chakraCostBase: 30,
    basePower: 40,
    complexityMultiplier: 1.4,
    powerMultiplier: 1.3,
    maxSafePower: 60,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Anclaje perceptivo'],
  },
  {
    id: 'mandalas_infinitos',
    name: 'Mandalas Infinitos',
    category: 'Genjutsu',
    mastery: 'USED',
    chakraCostBase: 45,
    basePower: 60,
    complexityMultiplier: 1.6,
    powerMultiplier: 1.5,
    maxSafePower: 80,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Anclaje perceptivo avanzado'],
  },
  {
    id: 'mirada_del_caos',
    name: 'Mirada del Caos',
    category: 'Genjutsu',
    mastery: 'CONFIRMED',
    chakraCostBase: 40,
    basePower: 65,
    complexityMultiplier: 1.6,
    powerMultiplier: 1.5,
    maxSafePower: 85,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Kali Mudra'],
  },
  {
    id: 'muerte_subita',
    name: 'Muerte Súbita',
    category: 'Genjutsu',
    mastery: 'USED',
    chakraCostBase: 50,
    basePower: 75,
    complexityMultiplier: 1.7,
    powerMultiplier: 1.6,
    maxSafePower: 90,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Intōn de Información'],
  },
  {
    id: 'loto_del_trauma',
    name: 'Loto del Trauma',
    category: 'Genjutsu',
    mastery: 'USED',
    chakraCostBase: 55,
    basePower: 80,
    complexityMultiplier: 1.75,
    powerMultiplier: 1.7,
    maxSafePower: 95,
    executionTimeSeconds: 2.5,
    knownByRin: true,
    requirements: ['Muerte Súbita'],
  },
  {
    id: 'loop_temporal_simple',
    name: 'Loop Temporal Simple',
    category: 'Genjutsu',
    mastery: 'USED',
    chakraCostBase: 60,
    basePower: 70,
    complexityMultiplier: 1.8,
    powerMultiplier: 1.6,
    maxSafePower: 90,
    executionTimeSeconds: 3.0,
    knownByRin: true,
    requirements: ['Anclaje perceptivo', 'Yin avanzado'],
  },
  {
    id: 'loop_adaptativo',
    name: 'Loop Adaptativo',
    category: 'Genjutsu',
    mastery: 'EXPERIMENTAL',
    chakraCostBase: 75,
    basePower: 80,
    complexityMultiplier: 1.9,
    powerMultiplier: 1.8,
    maxSafePower: 100,
    executionTimeSeconds: 3.5,
    knownByRin: true,
    requirements: ['Loop Temporal Simple'],
  },
  {
    id: 'genjutsu_identidad_fundamentos',
    name: 'Genjutsu de Identidad — fundamentos',
    category: 'Genjutsu/Yin',
    mastery: 'STUDIED',
    chakraCostBase: undefined, // UNSET
    basePower: undefined, // UNSET
    complexityMultiplier: 1.95,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 4.0,
    knownByRin: true,
    requirements: ['Modo Yin', 'Kuishōmoden'],
  },

  // 3. DISCURSO MALDITO
  {
    id: 'discurso_maldito',
    name: 'Discurso Maldito',
    category: 'Técnica especial',
    mastery: 'CONFIRMED',
    chakraCostBase: 25,
    basePower: 55,
    complexityMultiplier: 1.45,
    powerMultiplier: 1.4,
    maxSafePower: 70,
    executionTimeSeconds: 0.5,
    knownByRin: true,
    requirements: ['Resonancia vocal'],
  },
  {
    id: 'discurso_desactiva_chakra',
    name: 'Desactiva todo tu chakra',
    category: 'Discurso Maldito',
    mastery: 'USED',
    chakraCostBase: 35,
    basePower: 70,
    complexityMultiplier: 1.6,
    powerMultiplier: 1.6,
    maxSafePower: 85,
    executionTimeSeconds: 0.8,
    knownByRin: true,
    requirements: ['Discurso Maldito'],
  },

  // 4. MOKUTON
  {
    id: 'mokubunshin',
    name: 'Mokubunshin',
    category: 'Mokuton',
    mastery: 'MASTERED',
    chakraCostBase: 30,
    basePower: 25,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.1,
    maxSafePower: 40,
    executionTimeSeconds: 1.0,
    maintenanceCostPerTurn: 5,
    knownByRin: true,
    requirements: ['Mokuton básico'],
  },
  {
    id: 'raices',
    name: 'Raíces',
    category: 'Mokuton',
    mastery: 'MASTERED',
    chakraCostBase: 20,
    basePower: 30,
    complexityMultiplier: 1.25,
    powerMultiplier: 1.2,
    maxSafePower: 50,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Mokuton básico'],
  },
  {
    id: 'barrera_de_madera',
    name: 'Barrera de madera',
    category: 'Mokuton',
    mastery: 'CONFIRMED',
    chakraCostBase: 35,
    basePower: 45,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.3,
    maxSafePower: 65,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Raíces'],
  },
  {
    id: 'piel_de_madera',
    name: 'Piel de madera',
    category: 'Mokuton',
    mastery: 'MASTERED',
    chakraCostBase: 25,
    basePower: 30,
    complexityMultiplier: 1.3,
    powerMultiplier: 1.2,
    maxSafePower: 45,
    executionTimeSeconds: 0.8,
    maintenanceCostPerTurn: 3,
    knownByRin: true,
    requirements: ['Barrera de madera'],
  },
  {
    id: 'serpientes_cazadoras',
    name: 'Serpientes Cazadoras',
    category: 'Mokuton',
    mastery: 'CONFIRMED',
    chakraCostBase: 35,
    basePower: 50,
    complexityMultiplier: 1.45,
    powerMultiplier: 1.4,
    maxSafePower: 70,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Raíces'],
  },
  {
    id: 'fruto_explosivo',
    name: 'Fruto Explosivo',
    category: 'Mokuton',
    mastery: 'CONFIRMED',
    chakraCostBase: 40,
    basePower: 70,
    complexityMultiplier: 1.5,
    powerMultiplier: 1.5,
    maxSafePower: 85,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Raíces', 'Chakra infundido'],
  },
  {
    id: 'espora_somnifera',
    name: 'Espora Somnífera',
    category: 'Mokuton',
    mastery: 'USED',
    chakraCostBase: 35,
    basePower: 45,
    complexityMultiplier: 1.5,
    powerMultiplier: 1.3,
    maxSafePower: 65,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Suiton', 'Mokuton'],
  },
  {
    id: 'bosque_almas_hambrientas',
    name: 'Bosque de las Almas Hambrientas',
    category: 'Mokuton',
    mastery: 'USED',
    chakraCostBase: 100,
    basePower: 85,
    complexityMultiplier: 1.8,
    powerMultiplier: 1.7,
    maxSafePower: 110,
    executionTimeSeconds: 4.0,
    maintenanceCostPerTurn: 15,
    knownByRin: true,
    requirements: ['Raíces avanzadas', 'Intōn'],
  },
  {
    id: 'ataud_de_madera',
    name: 'Ataúd de madera',
    category: 'Mokuton',
    mastery: 'CONFIRMED',
    chakraCostBase: 50,
    basePower: 65,
    complexityMultiplier: 1.6,
    powerMultiplier: 1.5,
    maxSafePower: 80,
    executionTimeSeconds: 2.5,
    knownByRin: true,
    requirements: ['Barrera de madera', 'Serpientes Cazadoras'],
  },

  // 5. ATAÚDES DE MOKUTON (TÉCNICAS MÁXIMAS)
  {
    id: 'ataud_muerte_velo',
    name: 'Ataúd de la Muerte — Velo',
    category: 'Técnica máxima',
    mastery: 'USED',
    chakraCostBase: 90,
    basePower: 75,
    complexityMultiplier: 1.85,
    powerMultiplier: 1.6,
    maxSafePower: 95,
    executionTimeSeconds: 3.5,
    knownByRin: true,
    requirements: ['Ataúd de madera', 'Genjutsu perceptivo'],
  },
  {
    id: 'ataud_muerte_ultimo_dios',
    name: 'Ataúd de la Muerte — Último Dios',
    category: 'Técnica máxima',
    mastery: 'USED',
    chakraCostBase: 130,
    basePower: 90,
    complexityMultiplier: 1.95,
    powerMultiplier: 1.8,
    maxSafePower: 110,
    executionTimeSeconds: 4.5,
    knownByRin: true,
    requirements: ['Ataúd de la Muerte — Velo'],
  },
  {
    id: 'ataud_muerte_luto',
    name: 'Ataúd de la Muerte — Luto',
    category: 'Técnica máxima',
    mastery: 'EXPERIMENTAL',
    chakraCostBase: 180,
    basePower: 100,
    complexityMultiplier: 2.0,
    powerMultiplier: 2.0,
    maxSafePower: 120,
    executionTimeSeconds: 5.0,
    knownByRin: true,
    requirements: ['Ataúd de la Muerte — Último Dios'],
  },

  // 6. INTON & YIN / YANG
  {
    id: 'inton_informacion',
    name: 'Intōn de Información',
    category: 'Yin',
    mastery: 'CONFIRMED',
    chakraCostBase: 15,
    basePower: undefined,
    complexityMultiplier: 1.4,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Yūrei no Keimyaku'],
  },
  {
    id: 'kuishomoden',
    name: 'Kuishōmoden',
    category: 'Yin',
    mastery: 'CONFIRMED',
    chakraCostBase: 25,
    basePower: undefined,
    complexityMultiplier: 1.55,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Intōn de Información'],
  },
  {
    id: 'yin_yang_conocimiento_divino',
    name: 'Yin/Yang: Conocimiento Divino',
    category: 'Yin/Yang',
    mastery: 'USED',
    chakraCostBase: 50,
    basePower: undefined,
    complexityMultiplier: 1.9,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 4.0,
    knownByRin: true,
    requirements: ['Kuishōmoden', 'Yin/Yang'],
  },
  {
    id: 'mokuton_putrefaccion',
    name: 'Mokuton/Intōn: Putrefacción',
    category: 'Yin/Mokuton',
    mastery: 'USED',
    chakraCostBase: 60,
    basePower: 75,
    complexityMultiplier: 1.75,
    powerMultiplier: 1.6,
    maxSafePower: 90,
    executionTimeSeconds: 2.5,
    knownByRin: true,
    requirements: ['Raíces', 'Pergamino de Orochimaru'],
  },
  {
    id: 'estilo_vitalidad',
    name: 'Estilo Vitalidad',
    category: 'Yin/Mokuton',
    mastery: 'USED',
    chakraCostBase: 50,
    basePower: 40,
    complexityMultiplier: 1.7,
    powerMultiplier: 1.3,
    maxSafePower: 60,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Mokuton/Intōn: Putrefacción'],
  },
  {
    id: 'transferencia_vitalidad',
    name: 'Transferencia de vitalidad',
    category: 'Yin/Mokuton',
    mastery: 'CONFIRMED',
    chakraCostBase: 45,
    basePower: 30,
    complexityMultiplier: 1.65,
    powerMultiplier: 1.2,
    maxSafePower: 50,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Estilo Vitalidad'],
  },

  // 7. NINJUTSU & RAITON
  {
    id: 'chidori',
    name: 'Chidori',
    category: 'Raiton',
    mastery: 'CONFIRMED',
    chakraCostBase: 55,
    basePower: 80,
    complexityMultiplier: 1.65,
    powerMultiplier: 1.7,
    maxSafePower: 95,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Raiton', 'Velocidad de carga'],
  },
  {
    id: 'chidori_falso',
    name: 'Chidori Falso',
    category: 'Raiton',
    mastery: 'CONFIRMED',
    chakraCostBase: 35,
    basePower: 55,
    complexityMultiplier: 1.5,
    powerMultiplier: 1.4,
    maxSafePower: 70,
    executionTimeSeconds: 1.0,
    knownByRin: true,
    requirements: ['Chidori', 'Mokubunshin'],
  },
  {
    id: 'espiral_maldita',
    name: 'Espiral Maldita',
    category: 'Ninjutsu',
    mastery: 'CONFIRMED',
    chakraCostBase: 40,
    basePower: 60,
    complexityMultiplier: 1.55,
    powerMultiplier: 1.5,
    maxSafePower: 75,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Control de chakra'],
  },
  {
    id: 'espiral_maldita_7_aspas',
    name: 'Espiral Maldita — 7 Aspas',
    category: 'Ninjutsu',
    mastery: 'USED',
    chakraCostBase: 70,
    basePower: 85,
    complexityMultiplier: 1.8,
    powerMultiplier: 1.8,
    maxSafePower: 100,
    executionTimeSeconds: 2.5,
    knownByRin: true,
    requirements: ['Espiral Maldita'],
  },
  {
    id: 'tamushaki',
    name: 'Tamushaki',
    category: 'Ninjutsu',
    mastery: 'CONFIRMED',
    chakraCostBase: 35,
    basePower: 50,
    complexityMultiplier: 1.5,
    powerMultiplier: 1.3,
    maxSafePower: 65,
    executionTimeSeconds: 0.5,
    knownByRin: true,
    requirements: ['Desplazamiento'],
  },
  {
    id: 'tamushaki_inverso',
    name: 'Tamushaki Inverso',
    category: 'Ninjutsu',
    mastery: 'USED',
    chakraCostBase: 55,
    basePower: 70,
    complexityMultiplier: 1.7,
    powerMultiplier: 1.6,
    maxSafePower: 85,
    executionTimeSeconds: 0.8,
    knownByRin: true,
    requirements: ['Tamushaki'],
  },

  // 8. DOMINIO SIMPLE & DEFENSA
  {
    id: 'dominio_simple_percepcion',
    name: 'Dominio Simple: Percepción',
    category: 'Defensa',
    mastery: 'CONFIRMED',
    chakraCostBase: 30,
    basePower: 10,
    complexityMultiplier: 1.55,
    powerMultiplier: 1.1,
    maxSafePower: 30,
    executionTimeSeconds: 1.0,
    maintenanceCostPerTurn: 5,
    knownByRin: true,
    requirements: ['Dominio Simple'],
  },
  {
    id: 'dominio_simple_chakra_infernal',
    name: 'Dominio Simple: Chakra Infernal',
    category: 'Defensa',
    mastery: 'USED',
    chakraCostBase: 45,
    basePower: 25,
    complexityMultiplier: 1.65,
    powerMultiplier: 1.3,
    maxSafePower: 45,
    executionTimeSeconds: 1.5,
    maintenanceCostPerTurn: 8,
    knownByRin: true,
    requirements: ['Dominio Simple: Percepción'],
  },

  // 9. TAIJUTSU & INVOCACIÓN
  {
    id: 'garras_de_mantis',
    name: 'Garras de Mantis',
    category: 'Taijutsu',
    mastery: 'MASTERED',
    chakraCostBase: 5, // Range 0-5
    basePower: 35,
    complexityMultiplier: 1.2,
    powerMultiplier: 1.2,
    maxSafePower: 50,
    executionTimeSeconds: 0.3,
    knownByRin: true,
    requirements: ['Estilo Mantis'],
  },
  {
    id: 'precision_milimetrica',
    name: 'Precisión Milimétrica',
    category: 'Taijutsu',
    mastery: 'MASTERED',
    chakraCostBase: 5,
    basePower: 45,
    complexityMultiplier: 1.35,
    powerMultiplier: 1.3,
    maxSafePower: 60,
    executionTimeSeconds: 0.4,
    knownByRin: true,
    requirements: ['Garras de Mantis'],
  },
  {
    id: 'kali_mudra',
    name: 'Kali Mudra — seis brazos',
    category: 'Taijutsu/Invocación',
    mastery: 'USED',
    chakraCostBase: 40,
    basePower: 75,
    complexityMultiplier: 1.7,
    powerMultiplier: 1.6,
    maxSafePower: 90,
    executionTimeSeconds: 1.5,
    knownByRin: true,
    requirements: ['Invocación de Kali'],
  },
  {
    id: 'invocacion_de_kali',
    name: 'Invocación de Kali',
    category: 'Invocación',
    mastery: 'CONFIRMED',
    chakraCostBase: 35,
    basePower: undefined, // UNSET
    complexityMultiplier: 1.5,
    powerMultiplier: 1.0,
    maxSafePower: undefined,
    executionTimeSeconds: 2.0,
    knownByRin: true,
    requirements: ['Contrato de Kali'],
  },
];

/**
 * Searches for a technique by ID or Name fuzzy match
 */
export function getTechniqueByIdOrName(query: string): TechniqueDefinition | undefined {
  const q = query.trim().toLowerCase();

  const exact = RIN_MASTER_TECHNIQUES.find(
    (t) => t.id.toLowerCase() === q || t.name.toLowerCase() === q
  );
  if (exact) return exact;

  return RIN_MASTER_TECHNIQUES.find(
    (t) => t.name.toLowerCase().includes(q) || q.includes(t.name.toLowerCase())
  );
}

/**
 * Filters techniques by category
 */
export function getTechniquesByCategory(categoryQuery: string): TechniqueDefinition[] {
  const cat = categoryQuery.trim().toLowerCase();
  return RIN_MASTER_TECHNIQUES.filter((t) => t.category.toLowerCase().includes(cat));
}
